#!/bin/bash
# greptabulator.sh [expression] [directory]
grep -hR $1 $2 | sort | uniq -c | sort -nr | \
awk '{typesum += 1; matchsum += $1; print} END {print typesum, "unique types"; print matchsum, "total matches"}' typesum=0 matchsum=0
