#!/usr/bin/env python

# http://gist.github.com/262826
# originally by edsu - original at http://inkdroid.org/bzr/bin/marc-tags

import pymarc 
import sys

stats = {}

def tally(r):
    for f in r.fields:
        stats[f.tag] = stats.get(f.tag, 0) + 1

records = 0
for filename in sys.argv[1:]:
    for r in pymarc.MARCReader(file(filename)):
        records += 1
        tally(r)

#pymarc.map_xml(get_stats, *sys.argv[1:])

for e in stats:
    print "%s : %s" % (e, stats[e])

print "%s total records" % records