#!/bin/bash
export FEDORA_IMAGE_DIR=$HOME/Documents/Yale/fedora-testing-image
export FEDORA_IMAGE_NAME=$FEDORA_IMAGE_DIR/fedora-3.2.1-solr-1.3.0-testing.dmg
export FEDORA_HOME=/Volumes/fedora-solr-testing/fedora
export CATLINA_HOME=$FEDORA_HOME/tomcat
hdiutil attach $FEDORA_IMAGE_NAME -shadow $FEDORA_IMAGE_NAME.shadow
